from django.urls import path
from auth_app.views import (
    RegisterView,
    ValidateFirebaseTokenView,
    UserEditView,
    get_csrf_token,
    ProductListView,
    ProductDetailView,
    CartView,
    WishlistView,
    NotificationView,
    AdminNotificationView,
    PurchaseView,
    AdminPurchaseView,
    QuickLinkView,
    CustomerInquiryView,
    PurchaseDetailView,
    TrackPackageView,
    BuyAgainView,
    UserDetailView,
    payment_callback,  # Add PesaPal callback
    pesapal_ipn,      # Add PesaPal IPN
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('user/profile/', UserDetailView.as_view(), name='user-profile'),
    path('accounts/validate-firebase-token/', ValidateFirebaseTokenView.as_view(), name='validate-firebase-token'),
    path('user/edit/', UserEditView.as_view(), name='user-edit'),
    path('accounts/csrf/', get_csrf_token, name='get-csrf'),
    path('products/', ProductListView.as_view(), name='products'),
    path('products/<str:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/<str:product_id>/', CartView.as_view(), name='cart-item'),
    path('cart/<str:product_id>/<str:size>/', CartView.as_view(), name='size-cart-item'),
    path('cart/clear/', CartView.as_view(), name='cart-clear'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    path('wishlist/<str:product_id>/', WishlistView.as_view(), name='wishlist-item'),
    path('notifications/', NotificationView.as_view(), name='notifications'),
    path('notifications/<str:id>/', NotificationView.as_view(), name='notification'),
    path('admin/notifications/', AdminNotificationView.as_view(), name='admin-notifications'),
    path('purchases/', PurchaseView.as_view(), name='purchases'),
    path('admin/purchases/<str:id>/', AdminPurchaseView.as_view(), name='admin-purchase'),
    path('admin/purchases/', AdminPurchaseView.as_view(), name='admin-purchases'),
    path('quicklinks/', QuickLinkView.as_view(), name='quicklinks'),
    path('quicklinks/<int:id>/', QuickLinkView.as_view(), name='quicklink-detail'),
    path('inquiries/', CustomerInquiryView.as_view(), name='inquiries'),
    path('inquiries/<int:id>/', CustomerInquiryView.as_view(), name='inquiry-detail'),
    path('purchases/<str:id>/', PurchaseDetailView.as_view(), name='purchase-detail'),
    path('purchases/<str:id>/track/', TrackPackageView.as_view(), name='track-package'),
    path('purchases/<str:id>/buy-again/', BuyAgainView.as_view(), name='buy-again'),
    path('purchase/', PurchaseView.as_view(), name='purchase'),
    path('admin/reports/', AdminPurchaseView.as_view(), name='admin-reports'),
    path('purchases/<str:id>/', AdminPurchaseView.as_view(), name='admin-order-detail'),
    path('payment-callback/', payment_callback, name='payment_callback'),
    path('pesapal-ipn/', pesapal_ipn, name='pesapal_ipn'),
]